export const actionTypes = {
  OPEN_MOVIE_MODAL: "OPEN_MOVIE_MODAL",
  OPEN_EMOTION_MODAL: "OPEN_EMOTION_MODAL",
  CLOSE_MOVIE_MODAL: "CLOSE_MOVIE_MODAL",
  CLOSE_EMOTION_MODAL: "CLOSE_EMOTION_MODAL",
};
